name: Deply to LosLucas

on:
  push:
    branches:
      - loslucas20201_ui
    workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env variables
          run: |
            echo "NEXT_PUBLIC_API_URL=${{ secrets.QA_API_URL }}" >> .env.local

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploying to Heroku
        with:
          heroku_api_key: "737608ea-81f9-47d0-80f3-029bf500167e"
          heroku_email: "jesus.reikel@gmail.com"
          heroku_app_name: "loslucasstreamingcuba2"
          buildpack: "https://github.com/mars/heroku-nextjs"
          env_file: ".env.local"
          branch: "loslucas20201_ui"
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: https://api.eventos.streamingcuba.com/api/v1
