name: Deply to Los Lucas

on:
  push:
    branches: [ loslucas20201_ui ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.QA_API_URL }}" >> .env.local

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploying to Los Lucas
        with:
          heroku_api_key: "737608ea-81f9-47d0-80f3-029bf500167e"
          heroku_email: "jesus.reikel@gmail.com"
          heroku_app_name: "loslucasstreamingcuba2"
          useforce: true
          dynamicFiles: false
          env_file: ".env.local"
          procfile: "web: npm run start:heroku"
          branch: "loslucas20201_ui"
          buildpack: "https://github.com/mars/heroku-nextjs"
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
