name: Deply to Heroku

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.PERSONAL_TELEGRAM_USER_ID }}
          token: ${{ secrets.NOTIFICATIONS_TELEGRAM_BOT_TOKEN }}

      - name: Create env variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.QA_API_URL }}" >> .env.local

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploying to Heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          useforce: true
          dynamicFiles: false
          env_file: ".env.local"
          procfile: "yarn start:heroku"
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.QA_API_URL }}
