name: Deploy to Heroku

on:
  push:
    branches:
      - loslucas20201_ui


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploying to Heroku
        with:
          heroku_api_key: "737608ea-81f9-47d0-80f3-029bf500167e"
          heroku_email: "jesus.reikel@gmail.com"
          heroku_app_name: "loslucasstreamingcuba2"
          buildpack: "https://github.com/mars/heroku-nextjs"
          branch: "loslucas20201_ui"
        env:
          NODE_ENV: production
