name: Send Telegram notifications
 
on:
  workflow_run:
    workflows:
      - "Deploy to StreamingCuba VPS"
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Send succeeded Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.PERSONAL_TELEGRAM_USER_ID }}
        token: ${{ secrets.NOTIFICATIONS_TELEGRAM_BOT_TOKEN }}
        args: The ${{ github.event.worflow_run.name }} result status is succeess.
        
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Send failure Telegram notification
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.PERSONAL_TELEGRAM_USER_ID }}
        token: ${{ secrets.NOTIFICATIONS_TELEGRAM_BOT_TOKEN }}
        args: The ${{ github.event.worflow_run.name }} result status is failed.


      

      